apiVersion: v1
kind: Namespace
metadata:
  name: rookia
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rookia-quota
  namespace: rookia
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
