apiVersion: v1
kind: Service
metadata:
  name: pgboss-pg
  namespace: rookia
  labels:
    app: pgboss-pg
spec:
  type: ClusterIP
  selector:
    app: pgboss-pg
  ports:
    - name: pg
      port: 5432
      targetPort: pg
      protocol: TCP
