---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-neon-rookia
  namespace: observability
spec:
  encryptedData:
    NEON_ROOKIA_PASSWORD: AgCCYPlkMsVHjNDM03skkF4HHoTi6829/8O/YBtlkRu2csUrBFXT2qkl+qDQVXoenoqb5yVtuVQjMvOLVDe7wr1Uk00LAyIFTEX4IFOne6Nc7Ic4BJtmJCxPBGGXoTv2XETFLaSNkClI1n9S7v7TuR0qzyOfpOYmsB34fPAY1gnjSSktOoX1Spf+1bvg7+U0xMUSpDdh74poHG1awDkrx61PDjPHftf4whINy3OfYuDO8r/mgL7OKo7CJo2A72L4X4ax+cnN/keHD4VR/4V1BB1bY8WjbJ6jxkkcSkN3wteNzTO/ACqfx1yLA5X/ztTRSUAvPjieIPLCSyGGabXNO/2Iy/C3Zr8i84wn5CP1fpOLChihNHTinHIXXN1eZKFY0EVtOcGfyWLd+39deBd+w6YbInZOHsBaURvE+5g4vh6ZIdLBXt1P/Os0ZvvcYrXdDczxXbLNirdg6y3Rwj7kPHW/0ZVrvxUP1ilzhJ03ktBbbd0SEoZ0td7Up8iODGx6EpeCEoG1+SS4lp89i2MH38XS4o2t0xLZXJGHR0MkaOPI9rA+qtUSS3IfuRTf2QiOu5lHhsDQB3UaK5R+s5rdiKmGWGdX+5PXbenScFQhWUmR3jz0bbE7kSnuwl1P4R1jwHoLbktBrB+iGle+PqfFC+a5ZSGkF5qSk5bezcnudfB2WQP1618rTPCOi7l0hJObOcaRT9kqB7STUxoe1ixo/GBlnPSeB6lzlEM6RcrR9X5tpNlfzTb7MRQRhU/Kk4eWAJe+/JGd6K2f/uAeEH2wIHaA
  template:
    metadata:
      name: grafana-neon-rookia
      namespace: observability
