---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-github-oauth
  namespace: observability
spec:
  encryptedData:
    GF_AUTH_GITHUB_CLIENT_ID: AgBpg2duogwvTkO17Cuzkp8AoeCDBH3BeV1gstPhoCEPfwdIjIWha76RlosyqzbxNNkJSi+HJnhWxLW9/wiScDMvyh2D2uoGcobP+It4auEMJh+kXcGqKVW3Z6W4aQnACovDYRsPI5l2fz3aJ6h40Zkg8AQUIiquERhFWYeOHbPHIEAG4bqDcj3NfhU+o9R17Zah+Y66RatRRLp448DS2AA0cJULtvCmHCiLCdM1gEtKsc2t5a2MD3sgMSj+vyOyMgFbfg1wFXbgPQOEWmsT50Go8K22eTUp2Lc+h1qZoDNEWNJ7vje3VXYWJfREJls3pYc/YiZZ8A9nR71O/RbXqrW2w5h80aUiBVjNWve1n5ta7Wwd+L7His2FOpswSkTwdlekpDCiWfz+t9/xtezj5Qyn7j1iCsze8f1VjnRq6XvMZAzGdKPmi8R4AMA/jUTCYPv6O+HBg9V06bg7WQaOjcGgeCKYL+lQ/70NPtR0tMw6RfowM3L68uBPYAfdu+VkEunKlvoKJarUKNW7TKCyOZ5M/Di9HlEF+cEAqPjzKZRsyc8kVDe4DIboZdlTx46r/KV9jZ0dXyNOtXKRl2tOM6zQ7Z5i65f3sE3c1uv00XzF8zFlsQJNW+EUNZr+yulvKazHqR6sn2ohb16km7i7VpP4R3YSfghM5FXqSGvq53dP80bVjZM3aKjiGrN28EoetLo9oJ87fPmt5eLDvtyToO0wDs9TjA==
    GF_AUTH_GITHUB_CLIENT_SECRET: AgAeNfa3WBGExJ+QpnoAGEPqD3qVnSqhzDONYd+d7wdvVPSbo9oNIbdoss5zyXEUpWgpIlWk2eH5GTgaX5ZA8mF66YJh08he1GBBktDZyM9NlqDRmXjTcThhM+GuAanefTG/v+kz9ZLXjPwczDMVeMsEGetyJUojI/el4vNTlLmWxw3gae4K3uVsCTZalphkyintL2e6bx9gUc2FbbiATlW8N3UYgCuZHhkrWyB1bG3n7v0Uw8Xw1lA1puyHyObUQt8SF9B5w9c/G/ua4E9X1sae2GSmzRgAchh1lPxQImZ3SFwSHCjl/PT+MoXRhx9KZN/WEkBpf1STOiUkoivHvi7pOAv+2cK5iyiedV9sZaMAR0gGekDo1WnmHTkE54NwtzcCSauFy5tNLA4RdUd5KiT5ytXEgyVUP4O+L8A5lqy9D37Vkb4QYAY/+YqPOIZbngfc0r7VZBvhlCW96dwJkhm3KEVh996XaS7RUpYeP2dRokTE5e2ha/Z95SwLkEBJXOUZIOSeEeYx68xL3KftLChOHBzyQYWOICM6VMawGBSswBl707A+GfWvnJG87amanxg/iqKyPFL6wxL1G0T/9Voi5gKGJZobC2gYMZuN8sgHVC3KKDna2UdoNYRIGwnV6XQ0wbTt5FdFwZH5/ydfk8AxTv7tE+nqK9q4ADc7gZrHFiAtv0fxrXVGdonx9sCgFtdmZQjyOAxu2wcPMlxeLEkvEwv8X407luewXTexTHuIwQG/VSjTVVSO
  template:
    metadata:
      name: grafana-github-oauth
      namespace: observability
