apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tally
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/everspader/homelab.git
    targetRevision: HEAD
    path: tenants/tally/manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: tally
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
