---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgAEDRFzZELm8EapzZrIkeWBnu1OR2y+WFqU3iBYTBXxWUB6jNDlx2LSDpg6R3sARIZnpLrnfJ6JJ736YAvXvn1V9Zrl7JVb2J6XwcxTQD6ikYMgepQQpymtsIuO9GNUJO8d4Lr7F0ru6DJxRaOYpcTlkYdII8aksHAjGxaxSBDIIIvXoYLvHRLTKj81LBNE09QHZDIOnWED73h30bjYLbNdnc0yl4iorn9yu/v43wVuylodJ8jUF/rBcrVMV4GlKo63e00YqFNbBkwT9q+66Ukz5upKmK4HjSo6KuNpT0m2EQ3HFDWCTkgnNFvJlQMXNxefsQWPVhXiCjSIpyPPGMgHV2NARMW23FRRWeubt4lEajTlf7u+5xxqqrszH9uOeHxfx9TLLWTqcEoysTob7l30UVRKwpgwWqKnGj6Tf0WJVV4qDAIavAsNzDC0k/vA/13lWRmFKiwt1EfdsRcM7Uo1Cc+OySQ7tEgGiRZlObi5YJKf1NTXhQBEHtLEtCwvA3WU5PIJxNUaiofHEvG2QnNpje57BmohtgDzvn0OOyzoUgNklpXwMkMRblkPTaPcHg43TpRwoyWV2CEyUPVH85eQL5e6drwGbNIq01qPyspGVWJiZnmX4Zp7ZcpNEWDoU4uI20VNwa9IWgEE0QN7l1O5E1TmvBVd7joX0Ib0Qfj4elsN75UQavnMgShbq8CKIFBrea4b+4Oc3AwzSoGQ3UH15qmnWstoA5VGKtj4zP/mqzZb/S91HD4llwRqkb4YNgPZ9hW2YWn+KLF6qGaRZp8QPub3LKjrElC382dPb8NfkTL0U2inFdy7laArYTnLAQWewTdEXSwL79qg661HeNek824KfJsQo6wEp9Iatzm1jAjDpetpptfHTNZH4oEcHhvqJh06bUMplsQFYbvk9AGI/JG2B1bzWDfpxP9IanSkTiJ7A5mO7Taw
  template:
    metadata:
      name: tunnel-token
      namespace: cloudflared
